version: 2

sources:
  - name: dbtvault_bigquery_demo
    database: steadfast-task-363413
    schema: staging
    tables:
      - name: repl_UK_customers
      - name: repl_US_customers
      - name: repl_UK_orders
      - name: repl_customer_wealth_brackets
